### ISSUE TITLE
create the auth effects/reducer/service/model

### ISSUE THREAD

**Issue by nathanBrenner** [SecretSantaNg2Python/secretSanta-www#4]
There's a lot to this, but once you do it a couple times, it becomes predictable.  Dig into the ngrx docs, the ngrx in 10 minute video on egghead is great.  Also recommend starting without the effects because you don't need the api at that point.  Definately recommend createing some simple apps like a todo app that uses just ngrx/store.

1. Create the user interface. In `./shared/models/user.interface.ts` export an interface named User with properties for full name, email, password, id.  Each should be of type string.

Next, do the same for `session.interface.ts`, with propertes for user and token.  Token is of type string, and user is of type User (you'll need to import User)

2. Create the session reducer like how you created the User interface.  In `./shared/models/session.reducer.ts` add:

```
import { ActionReducer, Action } from '@ngrx/store';

import { Session } from '../models/session.interface';

export const SESSION_ACTIONS = {
      REGISTER_USER: {
		ATTEMPT: 'SESSION_GET_USER_ATTEMPT',
		FAILURE: 'SESSION_GET_USER_FAILURE',
		SUCCESS: 'SESSION_GET_USER_SUCCESS'
	}
}
```

Define a default session:
```
const defaultSession: Session = {
    token: '',
    user: {
        email: ''
    }
}
```
(You'll need to add empty strings for the rest of the defaultSession.user properties, otherwise Typescript will not be happy)

Next create the reducer:
```
export const sessionReducer: ActionReducer<Session> = (state: Session = defaultSession, {type, payload}: Action) => {
	console.log('action', type, payload);
	switch(type){
		case SESSION_ACTIONS.REGISTER_ACCOUNT.SUCCESS:
			return Object.assign({}, state, {account: payload})
		default:
			return state;
	}
}
```

3. In terminal, run `ng g s auth`.  Move the service ts and spec files into `/shared/services`.  You'll need to import rxjs of, map, and catch.  I'll add in the common service with documentation on what each line does, as it's a lot of the same thing.

Define a method that would get instantiated if the user registration form was submitted.  It should look something like this:

```
  postUser(payload){
    // new user registration
    return this.commonService.post('user', payload, false)
      .map(res => {
        let body = res.json().user;
        localStorage.setItem('Authorization', body.token);
        return {
          type: SESSION_ACTIONS.REGISTER_USER.SUCCESS,
          payload: body
        }
      })
      .catch(res => Observable.of({
        type: ERROR_ACTIONS.REPORT_ERROR,
        payload: {
          action_type: SESSION_ACTIONS.REGISTER_USER.FAILURE,
          message: res.json().error
        }
      }))
  }
```

4. Create `auth.effect.ts`.  It should look something like this:

```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import { Actions, Effect } from '@ngrx/effects';

import { AuthService } from '../services/auth.service';
import { SESSION_ACTIONS } from '../reducers/session.reducer';

@Injectable()
export class AuthEffects {
	
	constructor(
		private authService: AuthService,
		private actions$: Actions,
	){}

	@Effect() postUser$ = this.actions$
		.ofType(SESSION_ACTIONS.REGISTER_USER.ATTEMPT)
		.map(action => action.payload)
		.switchMap(payload => this.authService.postUser(payload))
}
```

5. Add the service, effect, and reducer into the root module.  Look at the docs for that, ask me questions as they come up.  It's up to you if you want to make a dumb registration-input component.  You can certainly make the user registration form in the Registration component, because it won't be subscribing to the store, but it will dispatch the `SESSION_ACTIONS.REGISTER_USER.ATTEMPT` action with the payload that is the values from the form.  There's a couple different ways you can get the data from the form: You can avoid using the `<form>` altogether, where you have a set of inputs, like 
```
<input type="text #username placeholder="username">
<button (click)="onSubmitUser(username)">Submit</button>
```

or you get get into reactive forms.  The later is a little more complicated, but better overall. If you want to add form validation, you'll need to use reactive forms so you can take advantage of the single directional databinding.

**Comment by onphenomenon** [comment]
why shouldn't user id be a number?

**Comment by nathan-j-brenner** [comment]
I think it has to do with the response coming back as valid json.  It might be something we can change to type number

**Comment by nathan-j-brenner** [comment]
testing slack integration
